export PROJECT = test_cbor
include ../Makefile.tests_common

USEMODULE += cbor embunit embunit_textui

INCLUDES += -I$(RIOTBASE)/tests/unittests/embunit

DISABLE_MODULE += auto_init

include $(RIOTBASE)/Makefile.include
